name: beatSeller
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: "^3.1.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.6
  cached_network_image: ^3.2.3
  badges: ^3.1.1
  carousel_slider: ^4.2.1
  image_stack: ^2.1.1
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  cloud_firestore: ^4.7.1
  get:
  equatable:
  uuid: ^3.0.5
  flutter_smart_dialog: ^4.3.6
  just_audio: ^0.9.21
  audio_service: ^0.18.4
  firebase_database: ^10.2.2
  freezed_annotation: ^2.0.3
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  intl: ^0.17.0
  tuple: ^2.0.0
  formz: ^0.4.1
  firebase_storage: ^11.2.2
  file_picker: ^4.6.1
  image_picker: ^0.8.5+3
  flutter_animated_dialog: ^2.0.1
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  freezed: ^2.0.3+1
  build_runner: ^2.1.11
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
